package programming11.friendsbook;

public class Friends {

    //Class to hold friends information - Name, age, gender, city, phone
    private String friendName;
    private Integer age = 0;
    private String gender = "";
    private String city = "";
    private String phoneNumber = "";
    //IN the future add an image
    //private File imageFile;

    //Constructors

    public Friends(String name, Integer age, String gender, String city, String phoneNumber) {
        this.friendName = name;
        this.age = age;
        this.gender = gender;
        this.city = city;
        this.phoneNumber = phoneNumber;
    }

    //Methods

    //Getters and Setters - autogenerated


    public String getFriendName() {
        return friendName;
    }

    public void setFriendName(String name) {
        this.friendName = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}
